openapi: 3.0.0
info:
  title: No components
  version: 1.0.0
servers:
- url: http://petstore.swagger.io/api
paths:
  /simpleRoute:
    post:
      summary: Exercise oneOf composition
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimpleRequest'
        description: The request body
        required: true
      responses:
        '201':
          description: OK

components:
  schemas:
    SimpleRequest:
      type: object
      required:
      - simpleString
      properties:
        simpleString:
          type: string
        simpleInt:
          type: integer
